server:
  port: 2333
  address: 0.0.0.0 # Railway 외부 접근 허용

lavalink:
  server:
    password: YOUR_PASSWORD_HERE # 봇에서 사용할 Lavalink 비밀번호
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    gc-warnings: true

logging:
  file:
    path: ./logs/
  level:
    root: INFO
    lavalink: INFO

